### ISSUE TITLE
Realtime Linting

### ISSUE THREAD

**Issue by DanielRojasC** [bancolombia/dart-code-linter#20]
**Description**
Dart-code-linter is based on Dart Code Metrics and that package have the realtime linting that show you on code the possible fixes that you have to add on your code. 

Currently i'm using the last free version of Dart Code Metrics and i've the analysis_options.yml, i tried to add dart-code-linter and use the same yml file change the plugin from dart-code-metrics to dart-code-linter (with the same rules) and this package not show any fix on my code but when i come back to dart-code-metrics it shows some recommended fixex based on rules.

There's something that i'm doing wrong? You're planning to add the real time linting to show on console and in code the recommended fixex on later versions 

Examples
![image](https://github.com/bancolombia/dart-code-linter/assets/41912789/085542d7-b50e-491b-96c8-1ba512b5e8c4)

Thanks for your support

**Comment by quoc-huynh-cosee** [comment]
Having the same problem. Any idea why? @santitigaga

**Comment by quoc-huynh-cosee** [comment]
I think the real time linting only works on Android Studio with the [DCM plugin](https://plugins.jetbrains.com/plugin/20856-dcm). To have real time linting with DCL, we need the equivalent of this plugin. Not sure if we can fork this plugin anywhere.

**Comment by nishiths23** [comment]
Any updates on this? Seems to be working on VSCode but not on Android Studio

**Comment by santitigaga** [comment]
Hey guys, sorry for the delay... 
however, @byshy is working on an Android plugin that can help us with real-time linting.

If @byshy want we can support that in the same project

**Comment by santitigaga** [comment]
@byshy did a good job and created a first release of the plugin, however updating flutter and android studio this works without the plugin

**Comment by byshy** [comment]
After starting to work on the plugin, I notice that my code was not working, but the IDE was highlighting all elements that has issues, I removed my work and opened the IDE, everything was still highlighted

These are the versions that I use

Flutter 3.24.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 603104015d (6 weeks ago) • 2024-10-24 08:01:25 -0700
Engine • revision db49896cf2
Tools • Dart 3.5.4 • DevTools 2.37.3

Android Studio Jellyfish | 2023.3.1
Build #AI-233.14808.21.2331.11709847, built on April 12, 2024
Runtime version: 17.0.10+0-17.0.10b1087.21-11572160 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 15.0.1
GC: G1 Young Generation, G1 Old Generation
Memory: 2304M
Cores: 12
Metal Rendering is ON
Registry:
  ide.experimental.ui=true
Non-Bundled Plugins:
  Statistic (4.3.1)
  com.intellij.marketplace (233.14808.24)
  com.bloc.intellij_generator_plugin (4.0.2)
  Dart (233.15271)
  com.github.byshy.flutterassistant (1.0.1)
  io.flutter (82.1.1)

AN IMPORTANT NOTE IS TO SET THE `analysis_options.yaml` CORRECTLY BY ADDING DCL AS A PLUGIN AND STATING THE RULES YOU WANT

Example
```yaml
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    
analyzer:
  exclude: [
    lib/generated/**,
    test/**/*.mocks.*
  ]

  plugins:
    - dart_code_linter

dart_code_linter:
  rules:
    - avoid-top-level-members-in-tests
    - avoid-collection-methods-with-unrelated-types
    - avoid-missing-enum-constant-in-map
    - avoid-unnecessary-type-assertions
    - avoid-unnecessary-type-casts
    - avoid-unused-parameters
    - newline-before-return
    - prefer-first-or-null
    - no-blank-line-before-single-return
    - no-boolean-literal-compare
    - no-empty-block
    - prefer-single-quotes
    - no-equal-then-else
    - prefer-async-await
    - prefer-correct-type-name:
        max-length: 44
    - prefer-match-file-name:
        exclude:
          - test/**
    - prefer-trailing-comma
```
